# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - VERSION="${BITBUCKET_BUILD_NUMBER}"
            - IMAGE=pidile007/${IMAGE_NAME}:latest
            - docker build . --file Dockerfile --tag ${IMAGE}
            - docker push "${IMAGE}"
            services:
              - docker
            caches:
              - docker
        - step:
            name: 'Sync to Github'
            script:
              - git remote add sync git@github.com:pidile007/mirthu-online-class.git
              - git checkout main
              - git pull
              - git push -f sync main
  
